version: "3"

services:
    chat-client:
        container_name: chat-client
        build:
            context: .
            dockerfile: ./apps/chat/Dockerfile
        restart: unless-stopped
        ports:
            - 32343:3000
        networks:
            - app_network

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
    app_network:
        external: true
