version: "3"

services:
    next:
        container_name: next
        build:
            context: .
            dockerfile: ./apps/next/Dockerfile
        restart: unless-stopped
        ports:
            - 43030:3000
        networks:
            - app_network

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
    app_network:
        external: true
