name: Update icons

on:
    push:
        branches:
            - master
        paths:
            - "packages/icon/**"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: marshallku/actions/setup-pnpm@master
            - name: Build icon
              run: pnpm build --filter @marshallku/icon
            - name: Check working tree
              run: |
                  file_changed=$(bash .github/scripts/check_working_tree.sh)

                  if [ "$file_changed" == 'false' ]; then
                    exit 0
                  fi
            - name: Update version of core package
              run: |
                  # Update version of icon
                  cd packages/icon
                  pnpm version patch

                  # Update version in dependencies
                  pnpm i @marshallku/icon@latest --filter @marshallku/docs

                  # Commit changes
                  cd ../..
                  bash .github/scripts/commit.sh
              env:
                  MESSAGE: "Update version of @marshallku/icon"
    send-notification:
        needs: [build]
        if: ${{ failure() }}
        uses: marshallku/actions/.github/workflows/send-notification.yml@master
        with:
            failed: ${{ contains(join(needs.*.result, ','), 'failure') }}
            message: "Failed to build icon"
        secrets:
            url: ${{ secrets.DISCORD_WEBHOOK_URI }}
