name: CI / Pull request

on:
    - pull_request

env:
    CI: true

jobs:
    check-code:
        name: Build and Test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - uses: marshallku/actions/setup-pnpm@master
            - run: bash .github/scripts/check_type.sh
              env:
                  BASE: ${{ github.base_ref }}
                  HEAD: ${{ github.head_ref }}
    lint:
        name: Check quality with ESLint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - uses: marshallku/actions/setup-pnpm@master
            - name: Check code quality
              run: pnpm eslint $(git diff --name-only --diff-filter=duxb origin/${{ github.base_ref }} origin/${{ github.head_ref }} | grep -E '\\.((j|t)sx?)$' | xargs)
    send-notification:
        needs: [check-code, lint]
        if: ${{ failure() }}
        uses: marshallku/actions/.github/workflows/send-notification.yml@master
        with:
            failed: ${{ contains(join(needs.*.result, ','), 'failure') }}
            message: "CI job failed - pull request"
        secrets:
            url: ${{ secrets.DISCORD_WEBHOOK_URI }}
