name: Deploy storybook

on:
    push:
        branches:
            - master
        paths:
            - "packages/ui/**"
            - "apps/docs/**"
    workflow_dispatch:

jobs:
    deploy:
        name: Deploy storybook to server
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - uses: marshallku/actions/setup-pnpm@master
            - name: Build storybook
              run: pnpm build --filter @marshallku/docs
            - name: Deploy to server
              uses: burnett01/rsync-deployments@6.0.0
              with:
                  switches: -avzr --delete
                  remote_path: ${{ secrets.STORYBOOK_PATH }}
                  remote_host: ${{ secrets.DEV_SERVER_HOST }}
                  remote_port: ${{ secrets.DEV_SERVER_PORT }}
                  remote_user: ${{ secrets.DEV_SERVER_USER }}
                  remote_key: ${{ secrets.SSH_KEY }}
                  path: /apps/docs/storybook-static
    send-notification:
        needs: [deploy]
        if: ${{ failure() }}
        uses: marshallku/actions/.github/workflows/send-notification.yml@master
        with:
            failed: ${{ contains(join(needs.*.result, ','), 'failure') }}
            message: "CI job failed - deploying storybook"
        secrets:
            url: ${{ secrets.DISCORD_WEBHOOK_URI }}
